spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: onlinemuseums
    url: jdbc:mysql://localhost:3306/onlinemuseums?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      jedis:
        pool:
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池的最大数据库连接数
          max-active: 8
          # 连接池中的最小空闲连接
          min-idle: 0
      timeout: 10s

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.school.onlinemuseums.entity

server:
  port: 8080
jwt:
  secret: what
  expiration: 10 # 设置为token的过期时间，单位为秒，这里设置为1小时
